#!/bin/bash
#
# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
cd "$(dirname "$0")/.."

REPO_VERSION=$(scripts/version)
DIST_VERSION=$((head -n 1 dist/marzipano.js || echo) | sed 's/.*(v\(.*\)).*/\1/')

if [[ "$REPO_VERSION" =~ "dev" ]] || [[ "$REPO_VERSION" != "$DIST_VERSION" ]]; then
  echo The current version cannot be published.
  echo Please ensure that the release was built from a clean working tree
  echo at a commit whose git tag matches the npm version.
  exit 1
fi
