import 'models/models.dart';

List<User> dummyUserList = [
  User(id: 1, email: 'aa@gmail.com', password: 'aa', userName: '이승주'),
  User(id: 1, email: 'bb@gmail.com', password: 'bb', userName: '박종현'),
  User(id: 1, email: 'cc@gmail.com', password: 'cc', userName: '이종완'),
  User(id: 1, email: 'dd@gmail.com', password: 'dd', userName: '임준혁'),
];
List<Event> dummyEventList = [
  Event(
    eventId: 1,
    eventName: '화양동 강도사건',
    eventStartedAt: '20201005',
    eventStatus: '기소완료',
    createdAt: '20200101',
    teamLeader: 1,
    teamMembers: [
      User(id: 1, email: 'aa@gmail.com', password: 'aa', userName: '이승주'),
      User(id: 1, email: 'bb@gmail.com', password: 'bb', userName: '박종현'),
      User(id: 1, email: 'cc@gmail.com', password: 'cc', userName: '이종완'),
      User(id: 1, email: 'dd@gmail.com', password: 'dd', userName: '임준혁'),
    ],
  ),
  Event(
    eventId: 2,
    eventName: '구의동 실종사건',
    eventStartedAt: '20200823',
    eventStatus: '수사중',
    createdAt: '20200101',
    teamLeader: 1,
    teamMembers: [
      User(id: 1, email: 'aa@gmail.com', password: 'aa', userName: '이승주'),
      User(id: 1, email: 'bb@gmail.com', password: 'bb', userName: '박종현'),
      User(id: 1, email: 'cc@gmail.com', password: 'cc', userName: '이종완'),
      User(id: 1, email: 'dd@gmail.com', password: 'dd', userName: '임준혁'),
    ],
  ),
  Event(
    eventId: 3,
    eventName: '서대문구 연쇄살인',
    eventStartedAt: '20200512',
    eventStatus: '수사중',
    createdAt: '20200101',
    teamLeader: 1,
    teamMembers: [
      User(id: 1, email: 'aa@gmail.com', password: 'aa', userName: '이승주'),
      User(id: 1, email: 'bb@gmail.com', password: 'bb', userName: '박종현'),
      User(id: 1, email: 'cc@gmail.com', password: 'cc', userName: '이종완'),
      User(id: 1, email: 'dd@gmail.com', password: 'dd', userName: '임준혁'),
    ],
  ),
  Event(
    eventId: 4,
    eventName: '중랑구 살인사건',
    eventStartedAt: '20200103',
    eventStatus: '현장감식 완료',
    createdAt: '20200101',
    teamLeader: 1,
    teamMembers: [
      User(id: 1, email: 'aa@gmail.com', password: 'aa', userName: '이승주'),
      User(id: 1, email: 'bb@gmail.com', password: 'bb', userName: '박종현'),
      User(id: 1, email: 'cc@gmail.com', password: 'cc', userName: '이종완'),
      User(id: 1, email: 'dd@gmail.com', password: 'dd', userName: '임준혁'),
    ],
  ),
  // Event('화양동사건1', '20200202', '서울시 광진구 아차산로 344 111호', '기소완료', dummyUserList[0],
  //     dummyUserList),
  // Event('자양동사건1', '20200503', '서울시 광진구 자양동 222 102호', '재판중', dummyUserList[1],
  //     dummyUserList),
  // Event('구의동사건1', '20200607', '서울시 광진구 구의동 183 404호', '기소 전', dummyUserList[2],
  //     dummyUserList),
  // Event('화양동사건2', '20200202', '서울시 광진구 아차산로 344 111호', '기소완료', dummyUserList[3],
  //     dummyUserList),
  // Event('자양동사건2', '20200503', '서울시 광진구 자양동 222 102호', '재판중', dummyUserList[0],
  //     dummyUserList),
  // Event('구의동사건2', '20200607', '서울시 광진구 구의동 183 404호', '기소 전', dummyUserList[0],
  //     dummyUserList),
];
List<Scene> dummySceneList = [
  Scene(
      sceneId: 1,
      sceneName: '피해자의 집',
      address1: '서울특별시 광진구 자양동',
      address2: '미래아파트 101동 202호',
      zip: '05023',
      createdAt: '20200202',
      fileId: '1'),
  Scene(
      sceneId: 2,
      sceneName: '현관',
      address1: '서울특별시 광진구 자양동',
      address2: '미래아파트 101동 202호',
      zip: '05023',
      createdAt: '20200202',
      fileId: '2'),
  Scene(
      sceneId: 3,
      sceneName: '아파트 입구',
      address1: '서울특별시 광진구 자양동',
      address2: '미래아파트 101동 202호',
      zip: '05023',
      createdAt: '20200202',
      fileId: '3'),
];
